AK_SPEAKER_SETUP_CONVERT_TO_SUPPORTED
AK_SPEAKER_SETUP_CONVERT_TO_SUPPORTED()
void AK_SPEAKER_SETUP_CONVERT_TO_SUPPORTED (AkUInt32 & io_uChannelMask) inline
Definition at line 244 of file AkSpeakerConfig.h.
References AK_SPEAKER_SETUP_FIX_LEFT_TO_CENTER(), and AK_SPEAKER_SETUP_FIX_REAR_TO_SIDE().
Referenced by AK::SetChannelConfigFromWaveFormatExtensible().