AkUnion
AkUnion()
template<typename T , class U_POOL , class uGrowBy , class TMovePolicy , class TComparePolicy > static bool AkUnion (AkSet< T, U_POOL, uGrowBy, TMovePolicy, TComparePolicy > & io_A, AkSetType & io_typeA, const AkSet< T, U_POOL, uGrowBy, TMovePolicy, TComparePolicy > & in_B, AkSetType in_typeB) inlinestatic
Definition at line 377 of file AkSet.h.
References AK_Success, AkIntersection(), AkSubtraction(), AkUnion(), AkArray< T, const T &, ArrayPoolDefault, AkGrowByPolicy_DEFAULT, AkAssignmentMovePolicy< T > >::Copy(), SetType_Exclusion, SetType_Inclusion, AkArray< T, const T &, ArrayPoolDefault, AkGrowByPolicy_DEFAULT, AkAssignmentMovePolicy< T > >::Term(), and AkArray< T, const T &, ArrayPoolDefault, AkGrowByPolicy_DEFAULT, AkAssignmentMovePolicy< T > >::Transfer().