AkDisjoint
AkDisjoint()
template<typename T , class U_POOL = ArrayPoolDefault, class uGrowBy , class TMovePolicy , class TComparePolicy > static bool AkDisjoint (const AkSet< T, U_POOL, uGrowBy, TMovePolicy, TComparePolicy > & in_A, const AkSet< T, U_POOL, uGrowBy, TMovePolicy, TComparePolicy > & in_B) static
Definition at line 97 of file AkSet.h.
References AkArray< T, const T &, ArrayPoolDefault, AkGrowByPolicy_DEFAULT, AkAssignmentMovePolicy< T > >::Begin(), and AkArray< T, const T &, ArrayPoolDefault, AkGrowByPolicy_DEFAULT, AkAssignmentMovePolicy< T > >::End().
Referenced by AkIntersect().