AkUnion
AkUnion()
template<typename T , class U_POOL , class uGrowBy , class TMovePolicy , class TComparePolicy > static bool AkUnion (AkSet< T, U_POOL, uGrowBy, TMovePolicy, TComparePolicy > & io_A, const AkSet< T, U_POOL, uGrowBy, TMovePolicy, TComparePolicy > & in_B) static
Definition at line 275 of file AkSet.h.
References AkCountIntersection(), AkArray< T, const T &, ArrayPoolDefault, AkGrowByPolicy_DEFAULT, AkAssignmentMovePolicy< T > >::Begin(), AkArray< T, const T &, ArrayPoolDefault, AkGrowByPolicy_DEFAULT, AkAssignmentMovePolicy< T > >::End(), AkArray< T, const T &, ArrayPoolDefault, AkGrowByPolicy_DEFAULT, AkAssignmentMovePolicy< T > >::Length(), AkArray< T, const T &, ArrayPoolDefault, AkGrowByPolicy_DEFAULT, AkAssignmentMovePolicy< T > >::Resize(), and AkArray< T, const T &, ArrayPoolDefault, AkGrowByPolicy_DEFAULT, AkAssignmentMovePolicy< T > >::Transfer().
Referenced by AkSubtraction(), and AkUnion().