AkAtomicLoad64
AkAtomicLoad64()
__forceinline long long AkAtomicLoad64 (AkAtomic64 * pSrc)
Definition at line 74 of file AkAtomic.h.
Referenced by AkFifoQueue< T, TDEFAULT, TAlloc >::Dequeue(), AkFifoQueue< T, TDEFAULT, TAlloc >::Empty(), and AkFifoQueue< T, TDEFAULT, TAlloc >::Enqueue().