AkRingBuffer::GetNbReadableItems
GetNbReadableItems()
template<class T , class TAlloc = AkRingBufferAllocatorDefault> AkUInt32 AkRingBuffer< T, TAlloc >::GetNbReadableItems () const inline
Definition at line 190 of file AkRingBuffer.h.
References AkAtomicLoad32().
Referenced by AkRingBuffer< T, TAlloc >::GetNbWritableItems(), AkRingBuffer< T, TAlloc >::Grow(), AkRingBuffer< T, TAlloc >::IncrementReadIndex(), AkRingBuffer< T, TAlloc >::Peek(), and AkRingBuffer< T, TAlloc >::ReadDataFromRing().