AkArray::FindEx
FindEx()
template<class T , class ARG_T , class TAlloc = ArrayPoolDefault, class TGrowBy = AkGrowByPolicy_DEFAULT, class TMovePolicy = AkAssignmentMovePolicy<T>> Iterator AkArray< T, ARG_T, TAlloc, TGrowBy, TMovePolicy >::FindEx (ARG_T in_Item) const inline
Returns the iterator th the specified item, will be End() if the item is not found.
Definition at line 362 of file AkArray.h.
Referenced by AkArray< T_MAPSTRUCT *, T_MAPSTRUCT *, ArrayPoolDefault, AkGrowByPolicy_NoGrow >::Exists(), AkArray< T_MAPSTRUCT *, T_MAPSTRUCT *, ArrayPoolDefault, AkGrowByPolicy_NoGrow >::Remove(), and AkArray< T_MAPSTRUCT *, T_MAPSTRUCT *, ArrayPoolDefault, AkGrowByPolicy_NoGrow >::RemoveSwap().