AK::AkFXParameterChangeHandler::m_uParamBitArray
m_uParamBitArray
template<AkUInt32 T_MAXNUMPARAMS> AkUInt8 AK::AkFXParameterChangeHandler< T_MAXNUMPARAMS >::m_uParamBitArray[(((T_MAXNUMPARAMS)+((8) -1)) &~((8) -1))/8] protected
Definition at line 98 of file AkFXParameterChangeHandler.h.
Referenced by AK::AkFXParameterChangeHandler< T_MAXNUMPARAMS >::HasAnyChanged(), AK::AkFXParameterChangeHandler< T_MAXNUMPARAMS >::HasChanged(), AK::AkFXParameterChangeHandler< T_MAXNUMPARAMS >::ResetAllParamChanges(), AK::AkFXParameterChangeHandler< T_MAXNUMPARAMS >::ResetParamChange(), AK::AkFXParameterChangeHandler< T_MAXNUMPARAMS >::SetAllParamChanges(), and AK::AkFXParameterChangeHandler< T_MAXNUMPARAMS >::SetParamChange().