AkDbString::Aquire
Aquire()
template<typename TAlloc , typename T_CHAR > template<typename TAlloc2 , typename T_CHAR2 > AKRESULT AkDbString< TAlloc, T_CHAR >::Aquire (const AkString< TAlloc2, T_CHAR2 > & in_str) inlineprotected
Definition at line 412 of file AkString.h.
References AK_Fail, AK_Success, AkHash(), AkString< TAlloc, T_CHAR >::AllocCopy(), AkString< TAlloc, T_CHAR >::Get(), AkDbString< TAlloc, T_CHAR >::m_uHash, AkDbString< TAlloc, T_CHAR >::Entry::refCount, AkDbString< TAlloc, T_CHAR >::Release(), and AkDbString< TAlloc, T_CHAR >::Entry::str.
Referenced by AkDbString< TAlloc, T_CHAR >::AkDbString(), and AkDbString< TAlloc, T_CHAR >::operator=().