AkArray::Length
Length()
template<class T , class ARG_T , class TAlloc = ArrayPoolDefault, class TGrowBy = AkGrowByPolicy_DEFAULT, class TMovePolicy = AkAssignmentMovePolicy<T>> AkForceInline AkUInt32 AkArray< T, ARG_T, TAlloc, TGrowBy, TMovePolicy >::Length () const inline
Returns the numbers of items in the array.
Definition at line 568 of file AkArray.h.
Referenced by AkArray< T_MAPSTRUCT *, T_MAPSTRUCT *, ArrayPoolDefault, AkGrowByPolicy_NoGrow >::AddLast(), AkArray< T_MAPSTRUCT *, T_MAPSTRUCT *, ArrayPoolDefault, AkGrowByPolicy_NoGrow >::BinarySearch(), AkArray< T_MAPSTRUCT *, T_MAPSTRUCT *, ArrayPoolDefault, AkGrowByPolicy_NoGrow >::Copy(), AkArray< T_MAPSTRUCT *, T_MAPSTRUCT *, ArrayPoolDefault, AkGrowByPolicy_NoGrow >::EraseSwap(), AkHashList< AkUInt32, Entry, TAlloc >::FindEx(), AkArray< T_MAPSTRUCT *, T_MAPSTRUCT *, ArrayPoolDefault, AkGrowByPolicy_NoGrow >::GrowArray(), AkHashList< AkUInt32, Entry, TAlloc >::HashSize(), AkHashListBare< T_KEY, T_MAPSTRUCT, T_ALLOC, KEY_POLICY >::HashSize(), AkArray< T_MAPSTRUCT *, T_MAPSTRUCT *, ArrayPoolDefault, AkGrowByPolicy_NoGrow >::Insert(), AkHashList< T_KEY, T_ITEM, T_ALLOC >::IteratorEx::operator++(), AkHashList< T_KEY, T_ITEM, T_ALLOC >::ConstIteratorEx::operator++(), AkHashListBare< T_KEY, T_MAPSTRUCT, T_ALLOC, KEY_POLICY, LIST_POLICY >::IteratorEx::operator++(), AkArray< T_MAPSTRUCT *, T_MAPSTRUCT *, ArrayPoolDefault, AkGrowByPolicy_NoGrow >::operator[](), AkArray< T_MAPSTRUCT *, T_MAPSTRUCT *, ArrayPoolDefault, AkGrowByPolicy_NoGrow >::ReserveExtra(), AkHashList< AkUInt32, Entry, TAlloc >::Resize(), AkHashListBare< T_KEY, T_MAPSTRUCT, T_ALLOC, KEY_POLICY >::Resize(), and AkArray< T_MAPSTRUCT *, T_MAPSTRUCT *, ArrayPoolDefault, AkGrowByPolicy_NoGrow >::Resize().