AkMatrix3x3::Rotation
Rotation()
static void AkMatrix3x3::Rotation (AkMatrix3x3 & out_mat, AkReal32 in_sin, AkReal32 in_cos, const Ak3DVector & in_axis) inlinestatic
Definition at line 1033 of file AkVectors.h.
References CrossProductMatrix(), Diagonal(), and OuterProduct().