T3DVector::DotProduct
DotProduct()
template<typename TDataType > AkForceInline TDataType T3DVector< TDataType >::DotProduct (const T3DVector< TDataType > & v2) const inline
Definition at line 607 of file AkVectors.h.
Referenced by AkPlane::DoesRayIntersect(), T3DVector< TReal >::Dot(), and AkBox::SeparatingAxisExists().