AkPlane::DoesRayIntersect
DoesRayIntersect()
bool AkPlane::DoesRayIntersect (const Ak3DVector & in_Origin, const Ak3DVector & in_Destination, Ak3DVector & out_Intersection) const inline
Definition at line 1424 of file AkVectors.h.
References T3DVector< TDataType >::DotProduct(), EPSILON, T3DVector< TDataType >::Length(), T3DVector< TDataType >::Normalize(), T3DVector< TDataType >::X, T3DVector< TDataType >::Y, and T3DVector< TDataType >::Z.