T3DVector::Normalize
Normalize()
template<typename TDataType > AkForceInline T3DVector& T3DVector< TDataType >::Normalize () inline
Definition at line 584 of file AkVectors.h.
Referenced by AkQuaternion::AkQuaternion(), AkPlane::DoesRayIntersect(), and AkPlane::FindIntersectionPoints().