AkAudioBuffer::GetChannel
GetChannel()
AkSampleType* AkAudioBuffer::GetChannel (AkUInt32 in_uIndex) inline
Get the buffer of the ith channel. To be used with de-interleaved buffers only.
Access to channel data is most optimal through this method. Use whenever the speaker configuration is known, or when an operation must be made independently for each channel.
Remarks
When using a standard Wwise pipeline configuration, use ChannelBitToIndex() to convert channel bits to buffer indices.
Returns
Address of the buffer of the ith channel.
See also
Accessing Data Using AkAudioBuffer Structure
Channel Ordering
Parameters
in_uIndex Channel index [0,NumChannels()-1]
Definition at line 427 of file AkCommonDefs.h.
References AKASSERT, MaxFrames(), NumChannels(), and pData.
Referenced by GetLFE(), and ZeroPadToMaxFrames().