AK::Win32::Device::ComputeId
ComputeId()
void AK::Win32::Device::ComputeId () inline
Definition at line 241 of file AkMMDevice.h.
References AK_INVALID_DEVICE_ID, AKPLATFORM::AkWideCharToChar(), AK::FNVHash< HashParams >::ComputeLowerCase(), idDevice, and pDevice.
Referenced by AK::Win32::DeviceEnumerator::GetDefaultDevice(), AK::Win32::DeviceCollection::Iterator::GetDevice(), and SetDevice().