AkAudioBuffer::ZeroPadToMaxFrames
ZeroPadToMaxFrames()
void AkAudioBuffer::ZeroPadToMaxFrames () inline
Can be used to transform an incomplete into a complete buffer with valid data. The invalid frames are made valid (zeroed out) for all channels and the validFrames count will be made equal to uMaxFrames.
Definition at line 449 of file AkCommonDefs.h.
References AKASSERT, AkMin, GetChannel(), MaxFrames(), NumChannels(), pData, and uValidFrames.
Referenced by AkFXTailHandler::HandleTail().