AkArray::GrowArray
GrowArray()
template<class T , class ARG_T , class TAlloc = ArrayPoolDefault, class TGrowBy = AkGrowByPolicy_DEFAULT, class TMovePolicy = AkAssignmentMovePolicy<T>> bool AkArray< T, ARG_T, TAlloc, TGrowBy, TMovePolicy >::GrowArray () inline
Definition at line 774 of file AkArray.h.
Referenced by AkArray< T_MAPSTRUCT *, T_MAPSTRUCT *, ArrayPoolDefault, AkGrowByPolicy_NoGrow >::AddLast(), AkArray< T_MAPSTRUCT *, T_MAPSTRUCT *, ArrayPoolDefault, AkGrowByPolicy_NoGrow >::GrowArray(), AkArray< T_MAPSTRUCT *, T_MAPSTRUCT *, ArrayPoolDefault, AkGrowByPolicy_NoGrow >::Insert(), AkArray< T_MAPSTRUCT *, T_MAPSTRUCT *, ArrayPoolDefault, AkGrowByPolicy_NoGrow >::Reserve(), AkHashList< AkUInt32, Entry, TAlloc >::Resize(), AkHashListBare< T_KEY, T_MAPSTRUCT, T_ALLOC, KEY_POLICY >::Resize(), and AkArray< T_MAPSTRUCT *, T_MAPSTRUCT *, ArrayPoolDefault, AkGrowByPolicy_NoGrow >::Resize().