AkBox::Init
Init()
void AkBox::Init (const Ak3DVector & in_center, const Ak3DVector & in_extent, const Ak3DVector & in_Front, const Ak3DVector & in_Up) inline
Definition at line 1844 of file AkVectors.h.
References AKASSERT, T3DVector< TDataType >::Cross(), T3DVector< TDataType >::Dot(), and T3DVector< TDataType >::Length().