CAkKeyArray::UnsetSwap
UnsetSwap()
template<class T_KEY , class T_ITEM , class U_POOL = ArrayPoolDefault, class TGrowBy = AkGrowByPolicy_DEFAULT, class TMovePolicy = AkAssignmentMovePolicy<MapStruct<T_KEY, T_ITEM> >> void CAkKeyArray< T_KEY, T_ITEM, U_POOL, TGrowBy, TMovePolicy >::UnsetSwap (T_KEY in_Key) inline
Definition at line 143 of file AkKeyArray.h.
References AkArray< MapStruct< T_KEY, T_ITEM >, const MapStruct< T_KEY, T_ITEM > &, ArrayPoolDefault, AkGrowByPolicy_DEFAULT, AkAssignmentMovePolicy< MapStruct< T_KEY, T_ITEM > > >::End(), AkArray< MapStruct< T_KEY, T_ITEM >, const MapStruct< T_KEY, T_ITEM > &, ArrayPoolDefault, AkGrowByPolicy_DEFAULT, AkAssignmentMovePolicy< MapStruct< T_KEY, T_ITEM > > >::EraseSwap(), and CAkKeyArray< T_KEY, T_ITEM, U_POOL, TGrowBy, TMovePolicy >::FindEx().