AkSortedKeyArray::BinarySearch
BinarySearch()
template<class T_KEY , class T_ITEM , class U_POOL = ArrayPoolDefault, class U_KEY = AkGetArrayKey< T_KEY, T_ITEM >, class TGrowBy = AkGrowByPolicy_DEFAULT, class TMovePolicy = AkAssignmentMovePolicy<T_ITEM>, class TComparePolicy = AkDefaultSortedKeyCompare<T_KEY>> T_ITEM* AkSortedKeyArray< T_KEY, T_ITEM, U_POOL, U_KEY, TGrowBy, TMovePolicy, TComparePolicy >::BinarySearch (T_KEY in_key, bool & out_bFound) const inline
Definition at line 575 of file AkKeyArray.h.
Referenced by AkSortedKeyArray< T, T, AkPluginArrayAllocator, AkSetGetKey< T >, AkGrowByPolicy_DEFAULT, AkAssignmentMovePolicy< T >, AkDefaultSortedKeyCompare< T > >::AddNoSetKey(), AkSortedKeyArray< T, T, AkPluginArrayAllocator, AkSetGetKey< T >, AkGrowByPolicy_DEFAULT, AkAssignmentMovePolicy< T >, AkDefaultSortedKeyCompare< T > >::Exists(), AkSortedKeyArray< T, T, AkPluginArrayAllocator, AkSetGetKey< T >, AkGrowByPolicy_DEFAULT, AkAssignmentMovePolicy< T >, AkDefaultSortedKeyCompare< T > >::Reorder(), and AkSortedKeyArray< T, T, AkPluginArrayAllocator, AkSetGetKey< T >, AkGrowByPolicy_DEFAULT, AkAssignmentMovePolicy< T >, AkDefaultSortedKeyCompare< T > >::Set().