AkArray::IsGrowingAllowed
IsGrowingAllowed()
template<class T , class ARG_T , class TAlloc = ArrayPoolDefault, class TGrowBy = AkGrowByPolicy_DEFAULT, class TMovePolicy = AkAssignmentMovePolicy<T>> bool AkArray< T, ARG_T, TAlloc, TGrowBy, TMovePolicy >::IsGrowingAllowed () const inline
Definition at line 511 of file AkArray.h.
Referenced by AkArray< T_MAPSTRUCT *, T_MAPSTRUCT *, ArrayPoolDefault, AkGrowByPolicy_NoGrow >::AddLast(), AkArray< T_MAPSTRUCT *, T_MAPSTRUCT *, ArrayPoolDefault, AkGrowByPolicy_NoGrow >::Insert(), and AkArray< T_MAPSTRUCT *, T_MAPSTRUCT *, ArrayPoolDefault, AkGrowByPolicy_NoGrow >::Reserve().