AkRingBuffer::WriteDataToRing
WriteDataToRing()
template<class T , class TAlloc = AkRingBufferAllocatorDefault> void AkRingBuffer< T, TAlloc >::WriteDataToRing (T * in_pSrc, AkUInt32 in_nbItems) inline
Definition at line 137 of file AkRingBuffer.h.
References AKASSERT, AkAtomicAdd32(), AKPLATFORM::AkMemCpy(), and AkRingBuffer< T, TAlloc >::GetNbWritableItems().