AkAudioBuffer::MaxFrames
MaxFrames()
AkForceInline AkUInt16 AkAudioBuffer::MaxFrames () const inline
Access to the number of sample frames the buffer can hold.
Returns
Number of sample frames the buffer can hold.
Definition at line 495 of file AkCommonDefs.h.
References uMaxFrames.
Referenced by GetChannel(), AkFXTailHandler::HandleTail(), AkFXDurationHandler::ProduceBuffer(), and ZeroPadToMaxFrames().