AK::Win32::Device::SetDevice
SetDevice()
void AK::Win32::Device::SetDevice (IMMDevice * in_pNew) inline
Definition at line 260 of file AkMMDevice.h.
References ComputeId(), and pDevice.
Referenced by Device(), and operator=().