AkDbString::GetFromHash
GetFromHash()
template<typename TAlloc , typename T_CHAR > static const T_CHAR* AkDbString< TAlloc, T_CHAR >::GetFromHash (AkUInt32 in_uHash) inlinestatic
Definition at line 323 of file AkString.h.
References AkHashList< T_KEY, T_ITEM, T_ALLOC >::Exists(), AkString< TAlloc, T_CHAR >::Get(), AkDbString< TAlloc, T_CHAR >::Entry::str, and AkDbString< TAlloc, T_CHAR >::Instance::table.
Referenced by AkDbWeakString< TAlloc, T_CHAR >::Get().