AkBox::SeparatingAxisExists
SeparatingAxisExists()
bool AkBox::SeparatingAxisExists (const Ak3DVector & L, const AkBox & B) const inline
Definition at line 1884 of file AkVectors.h.
References T3DVector< TDataType >::DotProduct(), GetCenter(), GetUx(), GetUy(), GetUz(), T3DVector< TDataType >::X, T3DVector< TDataType >::Y, and T3DVector< TDataType >::Z.