AK::ObjectPool::Allocate
Allocate()
template<typename T , typename AllocatorType = ObjectPoolDefaultAllocator<>, typename LockType = ObjectPoolDefaultLockType> AK_NODISCARD ValueType* AK::ObjectPool< T, AllocatorType, LockType >::Allocate () inline
Allocates a new object.
Returns
the object on success or nullptr if it fails (already full).
Definition at line 137 of file AkObjectPool.h.
References AK::ObjectPool< T, AllocatorType, LockType >::DataType::Data(), AK::ObjectPool< T, AllocatorType, LockType >::IsFull(), and AK::ObjectPool< T, AllocatorType, LockType >::DataType::next.
Referenced by AK::ObjectPool< T, AllocatorType, LockType >::AllocateZeroFilled().