AkSortedKeyArray::Lesser
Lesser()
template<class T_KEY , class T_ITEM , class U_POOL = ArrayPoolDefault, class U_KEY = AkGetArrayKey< T_KEY, T_ITEM >, class TGrowBy = AkGrowByPolicy_DEFAULT, class TMovePolicy = AkAssignmentMovePolicy<T_ITEM>, class TComparePolicy = AkDefaultSortedKeyCompare<T_KEY>> AkForceInline bool AkSortedKeyArray< T_KEY, T_ITEM, U_POOL, U_KEY, TGrowBy, TMovePolicy, TComparePolicy >::Lesser (const T_KEY & a, const T_KEY & b) const inline
Definition at line 209 of file AkKeyArray.h.
Referenced by AkSortedKeyArray< T, T, AkPluginArrayAllocator, AkSetGetKey< T >, AkGrowByPolicy_DEFAULT, AkAssignmentMovePolicy< T >, AkDefaultSortedKeyCompare< T > >::BinarySearch(), AkSortedKeyArray< T, T, AkPluginArrayAllocator, AkSetGetKey< T >, AkGrowByPolicy_DEFAULT, AkAssignmentMovePolicy< T >, AkDefaultSortedKeyCompare< T > >::LowerBounds(), AkSortedKeyArray< T, T, AkPluginArrayAllocator, AkSetGetKey< T >, AkGrowByPolicy_DEFAULT, AkAssignmentMovePolicy< T >, AkDefaultSortedKeyCompare< T > >::Reorder(), and AkSortedKeyArray< T, T, AkPluginArrayAllocator, AkSetGetKey< T >, AkGrowByPolicy_DEFAULT, AkAssignmentMovePolicy< T >, AkDefaultSortedKeyCompare< T > >::SortedUpdate().