AkFXDurationHandler::Setup
Setup()
void AkFXDurationHandler::Setup (AkReal32 in_fDuration, AkInt16 in_iLoopingCount, AkUInt32 in_uSampleRate) inline
Setup duration handler.
Parameters
in_fDuration Duration (in secs)
in_iLoopingCount Number of loop iterations (0 == infinite)
in_uSampleRate Sample rate
Definition at line 39 of file AkFXDurationHandler.h.
References m_uSampleRate, Reset(), SetDuration(), and SetLooping().