AK::IAkPluginServiceHashTable::RemoveSlotValue
RemoveSlotValue()
template<typename KeyType , typename ValueType > AkForceInline bool AK::IAkPluginServiceHashTable::RemoveSlotValue (AkHashTable< KeyType, ValueType > * io_pHashTable, AkInt32 in_iSlotToRemove) inline
Definition at line 170 of file IAkPluginHashTable.h.
References RemoveSlot(), and AK::AkHashTable< KeyType, ValueType >::ValueAt().
Referenced by RemoveIfValue().