AkRingBuffer::Grow
Grow()
template<class T , class TAlloc = AkRingBufferAllocatorDefault> bool AkRingBuffer< T, TAlloc >::Grow (AkUInt32 in_uGrowBy) inline
Definition at line 230 of file AkRingBuffer.h.
References AKPLATFORM::AkMemCpy(), AK::MemoryMgr::Free(), and AkRingBuffer< T, TAlloc >::GetNbReadableItems().