AkString::Get
Get()
template<typename TAlloc , typename T_CHAR > const T_CHAR* AkString< TAlloc, T_CHAR >::Get () const inline
Definition at line 120 of file AkString.h.
Referenced by AkHash(), AkString< AkPluginArrayAllocator, char >::AkString(), AkDbString< TAlloc, T_CHAR >::Aquire(), AkDbString< TAlloc, T_CHAR >::Get(), AkDbString< TAlloc, T_CHAR >::GetFromHash(), and AkString< AkPluginArrayAllocator, char >::operator=().