AkPluginArrayAllocator::GetAllocator
GetAllocator()
AkForceInline AK::IAkPluginMemAlloc* AkPluginArrayAllocator::GetAllocator () inlineprotected
Definition at line 212 of file IAkPluginMemAlloc.h.
Referenced by AkMixerInputMap< KEY, USER_DATA >::AddInput(), AkMixerInputMap< KEY, USER_DATA >::EraseSwap(), AkMixerInputMap< KEY, USER_DATA >::RemoveAll(), AkMixerInputMap< KEY, USER_DATA >::RemoveInput(), and TransferMem().