AkArray::Begin
Begin()
template<class T , class ARG_T , class TAlloc = ArrayPoolDefault, class TGrowBy = AkGrowByPolicy_DEFAULT, class TMovePolicy = AkAssignmentMovePolicy<T>> Iterator AkArray< T, ARG_T, TAlloc, TGrowBy, TMovePolicy >::Begin () const inline
Returns the iterator to the first item of the array, will be End() if the array is empty.
Definition at line 346 of file AkArray.h.
Referenced by AkHashList< AkUInt32, Entry, TAlloc >::BeginEx(), AkArray< T_MAPSTRUCT *, T_MAPSTRUCT *, ArrayPoolDefault, AkGrowByPolicy_NoGrow >::FindEx(), and AkArray< T_MAPSTRUCT *, T_MAPSTRUCT *, ArrayPoolDefault, AkGrowByPolicy_NoGrow >::RemoveAll().