AKPLATFORM::OutputDebugMsg
OutputDebugMsg()
void AKPLATFORM::OutputDebugMsg (const wchar_t * in_pszMsg) inline
Output a debug message on the console.
Definition at line 300 of file AkPlatformFuncs.h.
Referenced by AkPlane::FindIntersectionPoints(), AkLine::Intersect(), and OutputDebugMsgV().