AK::ConvertAkTransformToAkWorldTransform
ConvertAkTransformToAkWorldTransform()
AkWorldTransform AK::ConvertAkTransformToAkWorldTransform (AkTransform in) inline
Definition at line 435 of file Ak3DObjects.h.
References ConvertAkVectorToAkVector64(), AkTransform::OrientationFront(), AkTransform::OrientationTop(), AkTransform::Position(), and AkListenerPosition::Set().