AK::ChannelMaskToNumChannels
ChannelMaskToNumChannels()
static AkUInt8 AK::ChannelMaskToNumChannels (AkChannelMask in_uChannelMask) inlinestatic
Returns the number of channels of a given channel configuration.
Definition at line 268 of file AkSpeakerConfig.h.
References AKPLATFORM::AkPopCount().
Referenced by ChannelBitToIndex(), GetNumberOfAnglesForConfig(), SetChannelConfigFromWaveFormatExtensible(), AkChannelConfig::SetStandard(), AkChannelConfig::SetStandardOrAnonymous(), and AkChannelConfig::Standard().