AK::SetChannelConfigFromWaveFormatExtensible
SetChannelConfigFromWaveFormatExtensible()
AkChannelConfig AK::SetChannelConfigFromWaveFormatExtensible (const WaveFormatExtensible & in_wfmext) inline
Definition at line 291 of file AkWavDefs.h.
References AK_SPEAKER_SETUP_ALL_SPEAKERS, AK_SPEAKER_SETUP_CONVERT_TO_SUPPORTED(), ChannelMaskFromNumChannels(), ChannelMaskToNumChannels(), WaveFormatExtensible::dwChannelMask, extensibleWavFormat, WaveFormat::nChannels, AkChannelConfig::SetAmbisonic(), AkChannelConfig::SetStandard(), AkChannelConfig::SetStandardOrAnonymous(), WaveFormatExtensible::SubFormat, and WaveFormat::wFormatTag.