AK::HashTable::Internal::OccupiedProbe
OccupiedProbe()
AkInt32 AK::HashTable::Internal::OccupiedProbe (const bool * pbSlotOccupied, AkInt32 iSlot, AkInt32 iNumEntries) inline
Definition at line 66 of file AkHashTableFuncs.h.
References AKPLATFORM::AkBitScanForward64().
Referenced by AK::HashTable::GetFirstActiveSlot(), and AK::HashTable::GetNextActiveSlot().