AKPLATFORM::AkLimitedSpinForZero
AkLimitedSpinForZero()
void AKPLATFORM::AkLimitedSpinForZero (AkAtomic32 * in_pVal) inline
Definition at line 120 of file AkAtomicSpinFuncs.h.
References AkAtomicLoad32(), AK::g_fFreqRatio, and PerformanceCounter().
Referenced by AkSpinWaitForZero().