AK::MemoryMgr::Free
Free()
AKSOUNDENGINE_API void AK::MemoryMgr::Free (AkMemPoolId in_poolId, void * in_pMemAddress)
Free memory allocated with the memory manager.
See also
Memory Manager
Parameters
in_poolId ID of the memory category (AkMemID)
in_pMemAddress Pointer to the start of memory
Referenced by AkDelete(), AkKeyDataPtrStruct< T_KEY, T_DATA, T_ALLOC >::FreeData(), AkRingBuffer< T, TAlloc >::Grow(), AkArray< T_MAPSTRUCT *, T_MAPSTRUCT *, ArrayPoolDefault, AkGrowByPolicy_NoGrow >::GrowArray(), AkHashList< AkUInt32, Entry, TAlloc >::RemoveAll(), AkHashList< AkUInt32, Entry, TAlloc >::RemoveItem(), AkArray< T_MAPSTRUCT *, T_MAPSTRUCT *, ArrayPoolDefault, AkGrowByPolicy_NoGrow >::Term(), AkFifoQueue< T, TDEFAULT, TAlloc >::Term(), AK::ObjectPool< T, AllocatorType, LockType >::Term(), AkRingBuffer< T, TAlloc >::Term(), and AkStringData< TAlloc, char >::Term().