AKPLATFORM::AkMemCpy
AkMemCpy()
AkForceInline void AKPLATFORM::AkMemCpy (void * pDest, const void * pSrc, AkUInt32 uSize)
Platform Independent Helper for memcpy/memmove/memset.
Definition at line 118 of file AkPlatformFuncs.h.
Referenced by AK::IAkPluginServiceHashTable::AddKeyValue(), AkString< AkPluginArrayAllocator, char >::AllocCopy(), AkRingBuffer< T, TAlloc >::Grow(), AkRingBuffer< T, TAlloc >::ReadDataFromRing(), AkHybridAllocator< uBufferSizeBytes, uAlignmentSize, T_MEMID >::ReAlloc(), AkHybridAllocator< uBufferSizeBytes, uAlignmentSize, T_MEMID >::TransferMem(), AkRingBuffer< T, TAlloc >::WriteDataToRing(), and AK::WriteUnaligned().