ak_wwise_plugin_container::SdkVersionMinorMultiplier
SdkVersionMinorMultiplier()
constexpr static uint64_t ak_wwise_plugin_container::SdkVersionMinorMultiplier () inlinestaticconstexpr
Definition at line 68 of file PluginContainer.h.
References SdkVersionSubminorMax(), and SdkVersionSubminorMultiplier().
Referenced by MinorSdkVersion(), and SdkVersionMajorMultiplier().