AkChannelConfig::SetStandardOrAnonymous
SetStandardOrAnonymous()
AkForceInline void AkChannelConfig::SetStandardOrAnonymous (AkUInt32 in_uNumChannels, AkUInt32 in_uChannelMask) inline
Set channel config as either a standard or an anonymous configuration, specified with both a given channel mask (0 if anonymous) and a number of channels (which must match the channel mask if standard).
Definition at line 524 of file AkSpeakerConfig.h.
References AK_ChannelConfigType_Anonymous, AK_ChannelConfigType_Standard, AKASSERT, AK::ChannelMaskToNumChannels(), eConfigType, uChannelMask, and uNumChannels.
Referenced by AkChannelConfig(), and AK::SetChannelConfigFromWaveFormatExtensible().