AkFifoQueue::Dequeue
Dequeue()
template<typename T , T TDEFAULT, class TAlloc = ArrayPoolDefault> bool AkFifoQueue< T, TDEFAULT, TAlloc >::Dequeue (T & io_value) inline
Dequeues a value from the specified queue, copying it to io_value
Returns
true if a value was successfully dequeued, false otherwise (if false, io_value will not be written to)
Definition at line 138 of file AkFifoQueue.h.
References AkAtomicCas64(), AkAtomicLoad64(), and AkAtomicStore64().