AkAudioObject::TransferContents
TransferContents()
void AkAudioObject::TransferContents (AkAudioObject & in_src) inline
Moves object metadata (everything but the key) from another object.
Parameters
in_src Object from which metadata is moved.
Definition at line 116 of file AkAudioObject.h.
References arCustomMetadata, cumulativeGain, instigatorID, objectName, positioning, priority, AkArray< T, ARG_T, TAlloc, TGrowBy, TMovePolicy >::Transfer(), and AkString< TAlloc, T_CHAR >::Transfer().
Referenced by Transfer().