AkChannelConfig::HasLFE
HasLFE()
AkForceInline bool AkChannelConfig::HasLFE () const inline
Query if LFE channel is present.
Returns
True when LFE channel is present
Definition at line 634 of file AkSpeakerConfig.h.
References AK::HasLFE(), and uChannelMask.
Referenced by AkAudioFormat::HasLFE(), AkAudioBuffer::HasLFE(), and AkAudioBuffer::StandardToPipelineIndex().